# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbegame', '0002_auto_20160524_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitorjob',
            options={'verbose_name': 'SBE Monitor Job', 'verbose_name_plural': 'SBE Monitor Jobs'},
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='key_level',
            field=models.BigIntegerField(default=1, verbose_name='Key Access Level'),
        ),
    ]
