# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-23 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbegame', '0002_auto_20160818_0033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitorjob',
            options={'verbose_name': 'SBE Monitor Job', 'verbose_name_plural': 'SBE Monitor Jobs'},
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='key_level',
            field=models.BigIntegerField(default=1, verbose_name='Key Access Level'),
        ),
        migrations.RenameField(
            model_name='monitorjob',
            old_name='job_finish',
            new_name='finish',
        ),
        migrations.RenameField(
            model_name='monitorjob',
            old_name='job_host',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='monitorjob',
            old_name='job_monitor',
            new_name='monitor',
        ),
        migrations.RenameField(
            model_name='monitorjob',
            old_name='job_start',
            new_name='start',
        ),
    ]
