# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-25 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbegame', '0003_auto_20170323_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_last_played',
            new_name='last_played',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_players',
            new_name='players',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_registered',
            new_name='registered',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_score',
            new_name='score',
        ),
    ]
