# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-25 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbegame', '0004_auto_20170325_0450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostserver',
            old_name='server_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='hostserver',
            old_name='server_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_score',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_user',
            new_name='user',
        ),
    ]
