# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-25 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbegame', '0005_auto_20170325_0502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitorserver',
            old_name='monitor_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='monitorserver',
            old_name='monitor_key',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='monitorserver',
            old_name='monitor_name',
            new_name='name',
        ),
    ]
