# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-28 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbehost', '0016_auto_20170325_0458'),
        ('sbegame', '0006_auto_20170325_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorjob',
            name='host',
        ),
        migrations.AddField(
            model_name='monitorjob',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sbehost.GameService'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitorjob',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sbegame.MonitorServer'),
        ),
        migrations.AlterField(
            model_name='monitorjob',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Job Start'),
        ),
    ]
