# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-13 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbegame', '0007_auto_20170328_0136'),
        ('sbegame', '0003_auto_20160524_1155'),
    ]

    operations = [
    ]
