# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-18 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbegame', '0008_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorjob',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Job Start'),
        ),
    ]
