# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-04 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbehost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameteam',
            old_name='team_inst',
            new_name='team',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_teams',
        ),
        migrations.AddField(
            model_name='gameteam',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sbehost.Game'),
            preserve_default=False,
        ),
    ]
