# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbehost', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamecompromise',
            options={'verbose_name': 'SBE Host Compromise', 'verbose_name_plural': 'SBE Host Compromises'},
        ),
        migrations.AlterModelOptions(
            name='gamecontent',
            options={'verbose_name': 'SBE Service Content', 'verbose_name_plural': 'SBE Service Contents'},
        ),
    ]
