# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbehost', '0002_auto_20160524_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamehost',
            name='host_used',
        ),
        migrations.AddField(
            model_name='gamehost',
            name='host_value',
            field=models.SmallIntegerField(default=250, verbose_name='Host Value'),
        ),
        migrations.AlterField(
            model_name='gamehost',
            name='host_compromises',
            field=models.ManyToManyField(blank=True, to='sbehost.GameCompromise'),
        ),
        migrations.AlterField(
            model_name='gamehost',
            name='host_flags',
            field=models.ManyToManyField(blank=True, to='sbehost.GameFlag'),
        ),
        migrations.AlterField(
            model_name='gamehost',
            name='host_tickets',
            field=models.ManyToManyField(blank=True, to='sbehost.GameTicket'),
        ),
    ]
