# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-23 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbehost', '0002_auto_20161004_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamehost',
            name='host_value',
        ),
        migrations.AddField(
            model_name='gamehost',
            name='host_used',
            field=models.BooleanField(default=False, verbose_name=b'Host in Game'),
        ),
        migrations.AlterField(
            model_name='gamehost',
            name='host_compromises',
            field=models.ManyToManyField(to='sbehost.GameCompromise'),
        ),
        migrations.AlterField(
            model_name='gamehost',
            name='host_flags',
            field=models.ManyToManyField(to='sbehost.GameFlag'),
        ),
        migrations.AlterField(
            model_name='gamehost',
            name='host_tickets',
            field=models.ManyToManyField(to='sbehost.GameTicket'),
        ),
    ]
