# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-07 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbehost', '0004_gamehost_game_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehost',
            name='host_compromises',
            field=models.ManyToManyField(blank=True, null=True, to='sbehost.GameCompromise'),
        ),
    ]
