# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-17 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbehost', '0006_remove_gameteam_team_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameservice',
            name='game_host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sbehost.GameHost'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameteam',
            name='team_score_beacons',
            field=models.IntegerField(default=0, verbose_name=b'Team Score (Becons)'),
        ),
    ]
