# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-17 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbehost', '0007_auto_20161117_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamehost',
            name='host_compromises',
        ),
        migrations.AddField(
            model_name='gamecompromise',
            name='game_host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sbehost.GameHost'),
            preserve_default=False,
        ),
    ]
