# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-17 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbehost', '0008_auto_20161117_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecontent',
            name='game_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sbehost.GameService'),
            preserve_default=False,
        ),
    ]
