# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-17 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbehost', '0009_gamecontent_game_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameservice',
            name='service_content',
        ),
    ]
