# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-17 21:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbehost', '0010_remove_gameservice_service_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecompromise',
            name='comp_start',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Compromise Start'),
        ),
    ]
