# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-21 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbegame', '0002_auto_20160818_0033'),
        ('sbehost', '0011_auto_20161117_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameteam',
            name='team_flags',
        ),
        migrations.AddField(
            model_name='gameflag',
            name='flag_stealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flag_stealer', to='sbegame.Player'),
        ),
        migrations.AlterField(
            model_name='gameflag',
            name='flag_options',
            field=models.SmallIntegerField(choices=[(1, b'FLAG_TAKEN'), (2, b'FLAG_ENABLED'), (3, b'FLAG_HIDDEN'), (4, b'FLAG_PERMA')], default=2, verbose_name=b'Flag Options'),
        ),
        migrations.AlterField(
            model_name='gameflag',
            name='flag_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flag_owner', to='sbegame.Player'),
        ),
    ]
