# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-05 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbehost', '0011_auto_20161117_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehost',
            name='host_services',
            field=models.ManyToManyField(blank=True, to='sbehost.GameService'),
        ),
    ]
