# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-21 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbehost', '0012_auto_20161121_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameflag',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sbehost.Game'),
            preserve_default=False,
        ),
    ]
