# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-25 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbehost', '0015_auto_20170325_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecompromise',
            name='game_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sbehost.GameHost'),
        ),
        migrations.AlterField(
            model_name='gamecompromise',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sbegame.Player'),
        ),
        migrations.AlterField(
            model_name='gamecontent',
            name='data',
            field=models.TextField(blank=True, null=True, verbose_name=b'Data'),
        ),
        migrations.AlterField(
            model_name='gamecontent',
            name='http_verb',
            field=models.CharField(blank=True, choices=[(b'1', b'GET'), (b'2', b'POST')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='gamecontent',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
