# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-29 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbehost', '0016_auto_20170325_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecontent',
            name='connect_status',
            field=models.CharField(blank=True, choices=[(b'1', b'success'), (b'2', b'reset'), (b'3', b'timeout')], max_length=16, null=True),
        ),
    ]
