# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-09 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbehost', '0017_auto_20170329_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehost',
            name='ping_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamehost',
            name='ping_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameticket',
            name='reopened_count',
            field=models.IntegerField(default=0),
        ),
    ]
